[versions]
appcompat = "1.6.1"
compose-activity = "1.7.1"
compose-bom = "2022.10.00"
core-ktx = "1.10.1"
dagger-hilt = "2.46.1"
espresso-core = "3.5.1"
ext-junit = "1.1.5"
junit = "4.13.2"
lifecycle-runtime = "2.6.1"
material = "1.9.0"
compose-navigation = "2.5.3"
okhttp = "4.10.0"
retrofit = "2.9.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
espresso-core = { module = "androidx.test.espresso:espresso-core" , version.ref = "espresso-core"}
ext-junit = { module = "androidx.test.ext:junit" , version.ref = "ext-junit"}
junit = { module = "junit:junit", version.ref = "junit" }
junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime" }
material = { module = "com.google.android.material:material", version.ref = "material" }
moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
